name: Build image and push

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} my-registry/my-demo-image:${{ github.sha }}

    - name: Push to Registry
      run: echo "docker push my-registry/my-demo-image:${{ github.sha }}"

    - name: Download a scanner
      run: wget --user=${{ secrets.REG_USER }} --password=${{ secrets.REG_RASS }} https://download.aquasec.com/scanner/2401.3.18/scannercli -O ./scannercli

    - name: chmod 
      run: chmod 777 ./scannercli

    - name: Scan
      run: ./scannercli scan -H https://2635a139a3-d.cloud.aquasec.com/ -A ${{ secrets.SCANNER_TOKEN }} --local my-registry/my-demo-image:${{ github.sha }}
