name: Pull image and scan

env:
  CONSOLE_ADDRESS: https://europe-west3.cloud.twistlock.com/eu-158061
  IMAGE_NAME: greekgoods/kimura:1.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Pull the Docker image
      run: docker pull ${{ env.IMAGE_NAME }}

    - name: Upload tewistcli
      run: curl -u ${{ secrets.REG_USER }}:${{ secrets.REG_RASS }} --progress-bar -L ${{ env.CONSOLE_ADDRESS }}/api/v1/util/twistcli > twistcli; sudo chmod a+x twistcli;
        
    - name: Scan
      run: sudo ./twistcli sandbox --address ${{ env.CONSOLE_ADDRESS }} --user ${{ secrets.REG_USER }} --password ${{ secrets.REG_RASS }} --analysis-duration 2m ${{ env.IMAGE_NAME }}

  push:
    needs: build   
    runs-on: self-hosted
    steps: 
      - name: Push
        run: docker push ${{ env.IMAGE_NAME }}
