name: Build image and push

env:
  CONSOLE_ADDRESS: https://europe-west3.cloud.twistlock.com/eu-158061
  IMAGE_NAME: greekgoods/kimura:1.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Pull the Docker image
      run: docker pull ${{ env.IMAGE_NAME }}
        
    - name: Scan
      run: sudo twistcli sandbox --address ${{ env.CONSOLE_ADDRESS }} -u ${{ secrets.REG_USER }} -p ${{ secrets.REG_PASS }} --analysis-duration 2m ${{ env.IMAGE_NAME }}
      
