name: Build image and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Pull the Docker image
      run: docker pull greekgoods/kimura
        
    - name: Scan
      run: sudo twistcli sandbox --address https://europe-west3.cloud.twistlock.com/eu-158061 --token ${{ secrets.SCANNER_TOKEN }} --analysis-duration 2m greekgoods/kimura
      
